name: Node.js CI/CD (No Docker)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run lint/tests if you have them
      - name: Run lint
        run: npm run lint --if-present

      - name: Run tests
        run: npm test --if-present

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/deveraa-mail-api
            git pull origin main
            npm install --production
            pm2 restart mail-api || pm2 start server.js --name mail-api
